### ISSUE TITLE
Goal hit event is not triggered for goals added in level editor, even after they have been saved to the level file.

### ISSUE THREAD

**Issue by The-Renaissance** [tsoding/nothing#1018]
### Potentially related to #871 
After implementing the audio system, the sound is not played for hitting the goals added via the level editor, and if the player dies, it re-spawns at the goal previous to the added goal instead of the added goal. Sound right now only plays for the first goal in Level 1.

**Comment by The-Renaissance** [comment]
This is tested on the master binary as well. No difference, player doesn't respawn at goals added in level editor.

**Comment by The-Renaissance** [comment]
I think I found the issue...
The level editor simply adds the goal to the list and does nothing to the ebisp script in the level. For the event to trigger the visible attribute of the goal needs to be set to false, which nothing in the C source code does.
Here's the code that checks if the goal is hidden and sets the state to CUE_STATE_HIT_NOTHING (a prerequisite state for the sound play event):
```C
void goals_cue(Goals *goals,
               const Camera *camera)
{
    for (size_t i = 0; i < goals->count; ++i) {
        switch (goals->cue_states[i]) {
        case CUE_STATE_VIRGIN:
            if (goals_is_goal_hidden(goals, i) && camera_is_point_visible(camera, goals->positions[i])) {
                goals->cue_states[i] = CUE_STATE_HIT_NOTHING;
            }

            break;

        case CUE_STATE_SEEN_NOTHING:
            if (!goals_is_goal_hidden(goals, i) && camera_is_point_visible(camera, goals->positions[i])) {
                goals->cue_states[i] = CUE_STATE_VIRGIN;
            }
            break;

        default: {}
        }
    }
}
```
Here's the code in the level text file:
```lisp
(set args '())
(set jump-count 0)

(defun on-player-jump ()
  (set jump-count (+ jump-count 1))
  (when (> jump-count 3)
    (send `(game level label "label_space_to_jump" hide))))

(defun on-region-enter (region-id)
  ;; TODO(#880): Implement cond for ebisp
  (when (equal region-id "script_goal_1")
   (send `(game level goal "goal1" hide)))
  (when (equal region-id "script_show_goal_2")
   (send `(game level goal "goal2" show)))
  (when (equal region-id "script_hide_label_double_jump")
   (send `(game level label "label_double_jump" hide)))
  (when (equal region-id "hide_wasd_script")
   (send `(game level label "label_wasd" hide))))

(defun on-region-leave (region-id)
  (when (equal region-id "script_goal_1")
    (send `(game level goal "goal1" show))))
```
The default value for visible is `true`, and the visibility variable is only explicitly set to false in the ebisp script. The `visible` variable is only set to false  for goal 1.

**Comment by rexim** [comment]
@The-Renaissance thank you for researching this situation! Yes, it is by design.
