### ISSUE TITLE
Level's floating point values parsing may fail depending on system's locale.

### ISSUE THREAD

**Issue by destroycomputers** [tsoding/nothing#1019]
Haven't confirmed on other systems, but on macOS with system locale `ru_RU.UTF8` the level floating point values fail to parse due to use of '.' (dot) in them instead of ',' (comma). 

Empirically it was determined that the locale is reset from default "C" to system locale in `SDL_Init` call.

**Comment by The-Renaissance** [comment]
Have you switched your system locale to en_US to see if it's fixed?

**Comment by destroycomputers** [comment]
@The-Renaissance  I did not, but i `setlocale` it to "C" after the `SDL_Init` call and it worked!

**Comment by The-Renaissance** [comment]
@destroycomputers Could you submit a pull request for that? Thanks for the contribution!
