### ISSUE TITLE
LevelMetadata doesn't support multiple metadata

### ISSUE THREAD

**Issue by kolumb** [tsoding/nothing#1147]
As [mentioned](https://github.com/tsoding/nothing/issues/887#issuecomment-502388332) by @rexim, currently it supports only title. It must read version from level file to solve #452.

**Comment by rexim** [comment]
@kolumb sorry, I don't understand the point of this issue. Multiple metadata support is exactly what you have to do to address #452 and we already have an issue for #452.

**Comment by kolumb** [comment]
I just wanted to create issue before creating pr. That issue has purpose to check level version before loading level, and reject old versions. I thought that every problem has to have a separate issue.
Maybe in this case it's not standalone problem and better to create just pr.
