### ISSUE TITLE
Is it possible to incrementally rewrite this game in Nim

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#115]

**Comment by ForNeVeR** [comment]
So, what was the decision? Is it impossible? Or just not worth enough?

**Comment by rexim** [comment]
@ForNeVeR This issue was a result of me sidetracking again. The goal of this project is to deliver a simple game implemented purely in C. Nim is completely outside of the scope of this project.

**Comment by ForNeVeR** [comment]
Alright, fair enough!
