### ISSUE TITLE
Obsolete issues regarding ebisp

### ISSUE THREAD

**Issue by aodhneine** [tsoding/nothing#1155]
In 429efd78, ebisp was removed from nothing, and so this invalidates following issues: #341, #376, #445, #463, #466, #468, #626, because all of them refer to non-existing scripting language.
I believe that those issues should be closed, labeled as blocked or in other way marked as invalid, because otherwise new contributor might be confused by them.

**Comment by rexim** [comment]
@aodhneine thank you very much for this information! You helped the project a lot!

**Comment by zhiayang** [comment]
more: #335, #619, #651

**Comment by rexim** [comment]
@zhiayang yep, thank you very much! Transferred them to https://github.com/tsoding/ebisp
