### ISSUE TITLE
Levels created in game have the same title "New Level"

### ISSUE THREAD

**Issue by kolumb** [tsoding/nothing#1173]
### Steps to reproduce ###
1. Start game
1. Press `N`
1. Press `Tab`
1. Press `S`
1. Type level name
1. Press `Enter`
1. Repeat several times from step `1.`
1. Move created levels to assets dir
### Observed ###
All new levels have the same name "New Level".
![](https://i.imgur.com/cjiNRu9.jpg)
### Expected ###
List of level names which was typed while saving new levels.

**Comment by rexim** [comment]
Level titles were removed in #1203
