### ISSUE TITLE
Running the game in Windows Subsystem for Linux (Windows 10)

### ISSUE THREAD

**Issue by akhmadzaki** [tsoding/nothing#1174]
I am trying to run the game through Windows Subsystem for Linux (WSL) in Windows 10 64 bit. I have already followed the instruction for Linux and succeeded in building and compiling the program. But, when I try to run it, I got this error.

```
error: XDG_RUNTIME_DIR not set in the environment.
[FAIL] Could not initialize SDL: No available video device
```
Did i miss something or the game is not supported to run through WSL?

**Comment by rexim** [comment]
@akhmadzaki We do not actively test it on WSL, so, yeah, it's not officially supported. To be fair, I've never even ran it on WSL, so I have no idea how it works there. If you manage to fix this problem feel free to submit a PR with a code change or documentation update.

**Comment by akhmadzaki** [comment]
I followed the instruction from [here](https://www.howtogeek.com/261575/how-to-run-graphical-linux-desktop-applications-from-windows-10s-bash-shell/) and I can ran the game now. But, I got this message.

```
shared memfd open() failed: Function not implemented
[WARN] Could not find any Sticks of the Joy
[FAIL] No audio in 2019 LULW
[FAIL] init_buffer_and_device failed
```

**Comment by Honneamise** [comment]
@akhmadzaki currently WSL does not support audio, but you can enable it by installing the PulseAudio server.

You can found a step-by-step guide in this tutorial under the section **"Enabling Audio"** : 

[https://research.wmz.ninja/articles/2017/11/setting-up-wsl-with-graphics-and-audio.html](https://research.wmz.ninja/articles/2017/11/setting-up-wsl-with-graphics-and-audio.html)
