### ISSUE TITLE
Use newline for debug printing in rigid_bodies.c

### ISSUE THREAD

**Issue by ozy** [tsoding/nothing#1212]

**Comment by rexim** [comment]
@ozy 

- Firstly, could you please stop spamming similar issues? #1211
- Secondly, I don't remember ever explicitly saying that to submit a PR you need to have an issue for it. Just submit a PR next time and we will discuss it there. Read https://github.com/tsoding/contrib to learn what is expected from contributions.

**Comment by ozy** [comment]
Sorry, still trying to learn github.

**Comment by rexim** [comment]
@ozy ah, very well then. :)
