### ISSUE TITLE
Nothing doesn't start if SDL isn't built with haptic support

### ISSUE THREAD

**Issue by iv4nhoe** [tsoding/nothing#1225]
If SDL isn't build with haptic support `Nothing` doesn't start with following error:
```
[FAIL] Could not initialize SDL: SDL not built with haptic (force feedback) support
```
I guess Nothing doesn't use force feedback, so there shouldn't be a requirement for haptic support in SDL.

**Comment by rexim** [comment]
Resolved by #1226
