### ISSUE TITLE
Is the Linux style of typedefs applicable to this project?

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#212]
https://www.kernel.org/doc/html/latest/process/coding-style.html#typedefs

**Comment by ForNeVeR** [comment]
It's not clear what the "Linux style of typedefs" is. From the linked article, I have an impression that the "Linux style" is **not** using any typedefs.

**Comment by rexim** [comment]
@ForNeVeR the key points here is

> Lots of people think that typedefs `help readability`. Not so. They are useful only for:
> a. totally opaque objects (where the typedef is actively used to **hide** what the object is).
> ...

All of our [OOP entity types][oop] must be opaque types and we gonna keep using typedefs for them regardless of the outcome of this issue.

But we also have non-opaque types like [rect] or [point]. So the questions is should we use typedefs for them too? The arguments of Linux style sound pretty solid to me.

[oop]: https://github.com/tsoding/nothing/blob/0ad0f5bcdc11d48f62047fa8b52e017b2a950a2b/docs/oop.md#conventions
[rect]: https://github.com/tsoding/nothing/blob/0ad0f5bcdc11d48f62047fa8b52e017b2a950a2b/src/math/rect.h#L17
[point]: https://github.com/tsoding/nothing/blob/0ad0f5bcdc11d48f62047fa8b52e017b2a950a2b/src/math/point.h#L7

**Comment by rexim** [comment]
This is not going anywhere
