### ISSUE TITLE
The game drops the performance in the presence of OBS

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#251]

**Comment by rexim** [comment]
Especially on 60 FPS

**Comment by apa420** [comment]
Tried it on my machine, didn't have any significant performance differences when playing 30/60/144fps. (CPU: 4790K @ 4.5GHz and GPU: GTX1060 6GB)

**Comment by rexim** [comment]
@apa420 yeah, I don't experience it either after I enabled VAAPI support for OBS. It's a pretty old issue, thanks for reminding me about it! I think we can close it.
