### ISSUE TITLE
Console does not support Emacs keybindings */

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#355]

**Comment by TheKnarf** [comment]
Which Emacs-keybinding should one support?

**Comment by rexim** [comment]
- `C-f`
- `C-b`
- `M-f`
- `M-b`
- `C-n`, `C-p` (for history)
- `M-d`

Should be enough for now. Anything else can be done in the scope of separate issues.

**Comment by bepzi** [comment]
Done :) See PR #978 

History traversal is the only thing I didn't touch, because I wanted to limit my changes to only `edit_field.c` and I think history traversal was implemented somewhere else.

**Comment by rexim** [comment]
Resolved in #978
