### ISSUE TITLE
Making levels are not dependent on only C and SDL

### ISSUE THREAD

**Issue by TheKnarf** [tsoding/nothing#413]
Making levels are currently also dependent on `xqilla`, maybe the game could integrate an XML-parser directly so that we remove that 3rd party dependency.

**Comment by rexim** [comment]
@TheKnarf I think it's kinda limiting. What if we will need to generate levels not only from SVG? I like the idea of a native level format that you can generate from pretty much anything.

**Comment by TheKnarf** [comment]
While I don't disagree on having some sort of _native level format_, couldn't that be a flavor of XML? A lot of tools can output XML.

[Tiled](https://www.mapeditor.org/) is a populare map editor for 2D games that also uses an XML format. Converting from SVG to Tiled-xml should be fairly straight forvard.

Or one could invent a more fitting xml-format for your engine, and convert both SVG, Tiled-xml and other format into it.

**Comment by TheKnarf** [comment]
S-expression would be preferred, especially now that you have the parser implemented.
But can't I wish to have it both ways? To have my cake and eat it, too, so as to speak.

**Comment by rexim** [comment]
After #451 the game does not depend on xqilla anymore
