### ISSUE TITLE
Could not find any sticks of joy when controller not attached ?

### ISSUE THREAD

**Issue by fabulousduck** [tsoding/nothing#416]
OS: Ubuntu 18.04
Plugged in devices: mouse / keeb / headphone dongle

[WARNING] Could not find any Sticks of the Joy
libc error: Could not create the game object: No such file or directory

**Comment by rexim** [comment]
@fabulousduck since we figured out that it was because of the incorrectly provided file name, can we close this issue?

Error messages are garbage and I agree with that. I reported an issue for that #426.
