### ISSUE TITLE
labels causes build to fail

### ISSUE THREAD

**Issue by fabulousduck** [tsoding/nothing#427]
When defining a label using the text fields in inkscape, the game refuses to build.

SVG contents

https://pastebin.com/3XKvAf9X

**Comment by rexim** [comment]
@fabulousduck labels do not support newlines unfortunately. Try to use a separate label for each newline as a workaround. I'll see how we can improve svg2txt script to handle your case.

**Comment by rexim** [comment]
@fabulousduck I fixed the svg2rects failure in #431, but the labels still don't support newlines. We gonna fix it in #432 Please close this issue if the script does not fail on your svg anymore. Thanks!

**Comment by fabulousduck** [comment]
will try the patch out :D

**Comment by fabulousduck** [comment]
it seems to work
