### ISSUE TITLE
When opening the console using `c` it show `c` in the console

### ISSUE THREAD

**Issue by TheKnarf** [tsoding/nothing#428]
<img width="912" alt="screen shot 2018-10-14 at 22 21 26" src="https://user-images.githubusercontent.com/213777/46921750-816fd480-cfff-11e8-865a-ec09b6cb440b.png">

**Comment by fabulousduck** [comment]
typing c again closes it again unfortunately

**Comment by TheKnarf** [comment]
Maybe we could open the console with something like `ctrl+c`

**Comment by rexim** [comment]
@TheKnarf sounds like a duplicated of #404

**Comment by TheKnarf** [comment]
Feel free to mark it as duplicate issue and close it.
