### ISSUE TITLE
whitespace matters when not using s-expressions in console

### ISSUE THREAD

**Issue by fabulousduck** [tsoding/nothing#430]
`2*2` evaluates to a void variable
but
`2 * 2 ` evaluates to 2 ?

**Comment by TheKnarf** [comment]
Correct usage is `(+ 2 2)`, it's a lisp ;)

**Comment by fabulousduck** [comment]
bitch lasagna

**Comment by rexim** [comment]
@fabulousduck this is by design. `2*2` evaluates to a symbol with name `2*2`. `2 * 2` evaluates to just `2` because the rest of the expressions in the line are not parsed. And I think this is actually bug. I fixed it in the CLI REPL, but forgot about console.

**Comment by fabulousduck** [comment]
oh
lmao

i thought it was just me being stupid
