### ISSUE TITLE
Bind a script to a key

### ISSUE THREAD

**Issue by TheKnarf** [tsoding/nothing#445]
Would be nice for debugging purposes to quickly write a line of lisp and bind it to a key. Something like:

```
(bindkey F (add-force "player" '(0 -1000)))
```

**Comment by TheKnarf** [comment]
That seems to allow me to run it as `(f)` in the console, but I was looking to bind the `f` key (or any other key) in the game.

**Comment by rexim** [comment]
@TheKnarf We can actually make all of the game controls to be simply bindings to the scripting language and completely turn the game into Emacs.
