### ISSUE TITLE
Player climbs over huge steps if they consist of stack of smaller steps

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#49]
![out](https://user-images.githubusercontent.com/165283/34388660-942e2b80-eb67-11e7-9483-d2f205784646.gif)

[platforms.txt](https://github.com/tsoding/nothing/files/1619550/platforms.txt)

**Comment by rexim** [comment]
This is not something really critical, because can be pretty easily worked around on the level design level. Maybe we should consider this a feature.

**Comment by ForNeVeR** [comment]
That actually looks pretty nice. And I believe that's the way steps work in many other games (Doom, for example).

**Comment by ForNeVeR** [comment]
You may want to change the texture for the steps so they looks like "ladder". Also it shouldn't teleport the player instantly to the top (I believe currently it works that way?)

Overall it looks like an interesting feature, even if non-intentional.

**Comment by rexim** [comment]
By design
