### ISSUE TITLE
Ebisp does not have support for the map datastructure

### ISSUE THREAD

**Issue by TheKnarf** [tsoding/nothing#564]

**Comment by rexim** [comment]
@TheKnarf why do we need functions to construct something that does not exist in the language?

**Comment by TheKnarf** [comment]
I guess I was hoping for something like how maps work in Clojure.

># Maps
>Maps are commonly used for two purposes - to manage an association of keys to values and to represent domain application data. The first use case is often referred to as dictionaries or hash maps in other languages.
>
>## Creating a literal map
>Maps are represented as alternating keys and values surrounded by { and }.
>
>```
>(def scores {"Fred"  1400
>             "Bob"   1240
>             "Angela" 1024}
>```

ref https://clojure.org/guides/learn/hashed_colls#_maps

**Comment by rexim** [comment]
@TheKnarf in classical lisps for such purposes we usually use [Association Lists](https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node153.html), but we lack the `assoc` operation on the Ebisp side (it's already implemented on the C side). Would it suffice if we had `assoc`?

**Comment by TheKnarf** [comment]
I do like Clojure's solution where we add a bit of syntax for it since maps are such a common datastructure, but I guess I'd be happy with having `assoc` (at least as a first step).

**Comment by rexim** [comment]
@TheKnarf sorry, there are no plans to extend Ebisp syntax any further except for quasiquotes #572

**Comment by rexim** [comment]
Superseded by #573
