### ISSUE TITLE
Why no jitter?

### ISSUE THREAD

**Issue by JAremko** [tsoding/nothing#703]
Why it doesn't jitter when you zoom in?

**Comment by JAremko** [comment]
ok. Never-mind I found it out.

**Comment by rexim** [comment]
I believe you are refering to the rendering of the rectangles. The rendering of the rects happens in to steps:

https://github.com/tsoding/nothing/blob/deced0f20762d49c27a4233898a3c3be2b963194/src/game/camera.c#L73

- Mapping the rect to screen (according to camera position and scale)
- Converting rect to SDL_Rect, which effective converts all of the floats to ints
- And just rendering SDL_Rect with SDL

If the camera position and scale don't change between the frames, the end result of the rendering should be the same.
