### ISSUE TITLE
Remove pure-c tag

### ISSUE THREAD

**Issue by JAremko** [tsoding/nothing#726]
```
 C 90.3% CMake 4.7% Python 2.2% C++ 1.4% Objective-C 0.7% Common Lisp 0.2% Other 0.5%
```

# :roll_eyes:

**Comment by rexim** [comment]
C++ and Objective-C are bugs of GitHub (because they are supersets of C). Common Lisp is actually ebisp which we also developed in Pure C.

The only impurity we have is Python. Should we rewrite all of the Python code in C?

**Comment by JAremko** [comment]
We do what we must because we can (c)

**Comment by rexim** [comment]
@JAremko cool! Feel free to submit a Pull Request.

**Comment by rexim** [comment]
It's pure C now Pog
