### ISSUE TITLE
Documentation makes it look like you have to use svg2level directly to compile levels

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#848]
Reality is that you have to just use the corresponding Makefile. It would be even better if the level building was the part of the whole building process (there was an issue about that somewhere)

**Comment by kolumb** [comment]
> there was an issue about that somewhere

#763

**Comment by The-Renaissance** [comment]
@rexim you should close it as svg2rect is irrelevant at this point

**Comment by rexim** [comment]
@The-Renaissance yap! Thank you very much!
