### ISSUE TITLE
CRT secure warnings on Windows CI build

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#865]
Derived from #864 

Probably need to define `_CRT_SECURE_NO_WARNINGS`

**Comment by RIscRIpt** [comment]
Probably is going to be closed by #877, because `/D _CRT_SECURE_NO_WARNINGS` is going to be defined there, as these CRT warnings will become errors. And I doubt we would like to change the code base to use "secure" versions of C functions with suffix `_s`.

**Comment by rexim** [comment]
Resolved by #925
