### ISSUE TITLE
Jump events get dispatched when in GAME_STATE_PAUSE

### ISSUE THREAD

**Issue by cahe7cb** [tsoding/nothing#926]
While the game is paused, continuously pressing the jump key or button will apply jump force to the player's body making it fly very up high when the game is later unpaused.

Steps to reproduce: Pause the game while the player is resting on the ground. Press the jump action a few times. Unpause the game.

Result: The player will jump high up, proportionally to the amount of times the jump event was triggered.

Expected behavior: Player should keep its position after unpausing the game.

Seems like `game_event_pause` wrongfully(?) calls `level_event` when the game is paused.
Maybe related to #462

**Comment by rexim** [comment]
@cahe7cb lol that is funny! Thanks for report that! :) We will take a look.

**Comment by rexim** [comment]
@cahe7cb I cannot reproduce this on the latest version. Could you please check it one more time on the latest version when you get a chance?

**Comment by cahe7cb** [comment]
Yes, I can confirm. The problem is fixed and is no longer reproducible in latest master (
e40d288). Apparently it was fixed by the changes made in 6c4187e.

Feel free to close this issue.

**Comment by rexim** [comment]
@cahe7cb cool! Thank you so much!
