### ISSUE TITLE
Can't cmake on Parrot OS(Linux)

### ISSUE THREAD

**Issue by Petr73ru** [tsoding/nothing#949]
I do
  mkdir build && cd build
  cmake ..
and get "
  CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
"
I was trying  cmake -DSDL2_INCLUDE_DIR=/peter/local/include -SDL2 .. but the same is happened.

**Comment by rexim** [comment]
Looks similar to #923

@RIscRIpt what do you think? Could it be caused by the `REQUIRED` in `find_package`: https://github.com/tsoding/nothing/blob/250fbfbdef4f25f7beaf198feb4c1e01e6f56707/CMakeLists.txt#L16

Basically, cmake can't find `REQUIRED` package and fails before getting to the `SDL2::SDL2` workaround. Could that be the case?

**Comment by Petr73ru** [comment]
I deleted line 16 and got 2 errors:

**Comment by Petr73ru** [comment]
I think that  I was having libsdl2-dev not installed so after apt update and apt install libsdl2-dev everything worked.

**Comment by RIscRIpt** [comment]
> Looks similar to #923

Not really.

Look closely at

> The following error ... *(same error as above)* ... occurs on my linux machine when I don't have SDL2 installed (the same error is in MacOS CI).
