### ISSUE TITLE
Game crashes when trying to reload a new level

### ISSUE THREAD

**Issue by cahe7cb** [tsoding/nothing#957]
OS: Arch Linux
Git commit: 7d572ba

The game will crash when requested to reload a new level.

Steps to reproduce: On the main menu, press 'N' to create a new level, after the new level is created, press 'R' to reload the level.

Current behavior: The game will crash when trying to access the `file_name` of the level.

```
./nothing/src/game/level/level_editor.c:143: create_level_editor_from_file: Assertion `file_name' failed
Stacktrace: 
../build/nothing(__trace_assert+0x28)[0x556813bdbfb8]
../build/nothing(create_level_editor_from_file+0xe16)[0x556813bd5626]
../build/nothing(game_event+0x45d)[0x556813bbbfdd]
../build/nothing(main+0x34e)[0x556813bb98de]
/usr/lib/libc.so.6(__libc_start_main+0xf2)[0x7f757c4daee2]
../build/nothing(_start+0x2d)[0x556813bb9a8d]
```

**Comment by rexim** [comment]
@cahe7cb thank you for reporting this! We will take a look at it on the next Nothing stream :+1:
