### ISSUE TITLE
Level screen looks a bit weird on first load

### ISSUE THREAD

**Issue by TheKnarf** [tsoding/nothing#967]
On commit 4df5008, building on macOS.
Opening the game everything looks a bit weird:

<img width="912" alt="Screenshot 2019-07-21 at 18 22 45" src="https://user-images.githubusercontent.com/213777/61593814-ab84a180-abe4-11e9-9690-33df0c04a1f6.png">

But then after resizing it looks good:

<img width="969" alt="Screenshot 2019-07-21 at 18 22 49" src="https://user-images.githubusercontent.com/213777/61593816-ae7f9200-abe4-11e9-80aa-b676dfe789de.png">

**Comment by rexim** [comment]
That never happened to me. Probably because I use tiling wm that resizes the window right after starting the application. I'll try to check that on a non-tiling wm. 

Thanks for reporting that!

**Comment by TheKnarf** [comment]
I imagine this never get ran then: https://github.com/tsoding/nothing/blob/master/src/game/level_picker.c#L153

**Comment by rexim** [comment]
Resolved by #969
