### ISSUE TITLE
Game does not support High DPI screens

### ISSUE THREAD

**Issue by zhiayang** [tsoding/nothing#974]
On high dpi screens (eg. mac retina displays), everything looks kinda bad because it's literally scaled up 2x.

There's some stuff to do to fix it:

1. Pass the `SDL_WINDOW_ALLOW_HIGHDPI` flag to `SDL_CreateWindow`. This makes the game render at the same *window size*, but the "viewport size" is now double (or 3x or whatever the dpi scale is).

2. All operations on mouse coordinates need to be scaled by 2x. For example, `event->motion.x` needs to change to `event->motion.x * DPI_SCALE`. I believe the click coordinates (`event->button.x`) need to be scaled as well.

item (1) is a simple change, but I'm not sure how to do (2) in a "clean" way, without like passing extra parameters to all the event handlers (due to how intertwined the code is with SDL since it uses the event data directly). The other option is some kind of global state, but idk how you feel about that.

**Comment by TheKnarf** [comment]
Feel free to assign the issue to me @rexim
